image: node:22
stages:
  - install
  - typecheck
  - lint
  - test
  - build
  - deploy

# install:
#   stage: install
#   script:
#     - npm ci
#   artifacts:
#     paths:
#       - node_modules/

# typecheck:
#   stage: typecheck
#   dependencies:
#     - install
#   script:
#     - npm run typecheck

# lint:
#   stage: lint
#   image: node:22
#   dependencies:
#     - install
#   script:
#     - npm run lint
# test:
#   stage: test
#   dependencies:
#     - install
#   script:
#     - npm run test
# build:
#   stage: build
#   dependencies:
#     - install
#   script:
#     - npm run build

deploy:
  stage: deploy
  before_script:
    - npm install -g @railway/cli

  script:
    - railway up --service=$RAILWAY_SERVICE
